## spectrogram parameters ##
nsim = 1 # number of generated background
savefile = False # save the bursts
filename = 'simulatedbursts.pkl'

# frequency
freq_high = 1518 # frequency center in MHz
bw = 288  # in MHz
nchan = 96 # number of frequency channel
#freq_res = bw/nchan # frequency resolution in MHz

# Time
tres = 1 # in ms
ntsamp = 500 # number of sample in time axis

# Dspectrum
# The noise is a generated by a simple covariance kernel
hmeans = [0.1,0.15]
lammeans = [0.2,1] # mean lamda coefficient for multivariate
sigmrng = [0.01,0.1]
murng = [0.8,1.2]

# pulse profile
width_rng = [5,30] # in ms
fluence_rng = [3,6] # Jy ms
#tau_rng = [0.2,1]
snr_rng = [3,10] # signal to noise ratio range
dm_rng = [200,500] # in pc cm^3
peak_location = [30,70] # in image scale
burst_bw = [90,nchan]  # in image scale
#tarr = [0,int(ntsamp/2)]

# add rfi
#rfi = False # add rfi or not
